---
title: "CodeBook"
author: "Selvam R Sendhil"
date: "7/1/2019"
output: html_document
---

# Code Book

This code book summarizes the resulting data fields in `tidy.txt`.

## Identifiers

* `subject` - The ID of the test subject
* `activity` - The type of activity performed when the corresponding measurements were taken

## Activity Labels

* `WALKING` (value `1`): subject was walking during the test
* `WALKING_UPSTAIRS` (value `2`): subject was walking up a staircase during the test
* `WALKING_DOWNSTAIRS` (value `3`): subject was walking down a staircase during the test
* `SITTING` (value `4`): subject was sitting during the test
* `STANDING` (value `5`): subject was standing during the test
* `LAYING` (value `6`): subject was laying down during the test

## Measurements

* `TimeBodyAccelerometermeanX`                  
* `TimeBodyAccelerometermeanY`                   
* `TimeBodyAccelerometermeanZ`

* `TimeGravityAccelerometermeanX`               
* `TimeGravityAccelerometermeanY`                
* `TimeGravityAccelerometermeanZ`  

* `TimeBodyAccelerometerJerkmeanX`                
* `TimeBodyAccelerometerJerkmeanY`               
* `TimeBodyAccelerometerJerkmeanZ`

* `TimeBodyGyroscopemeanX`                       
* `TimeBodyGyroscopemeanY`                        
* `TimeBodyGyroscopemeanZ`    
                   
* `TimeBodyGyroscopeJerkmeanX`                    
* `TimeBodyGyroscopeJerkmeanY`                  
* `TimeBodyGyroscopeJerkmeanZ`    

* `TimeBodyAccelerometerMagmean`                 
* `TimeGravityAccelerometerMagmean`              
* `TimeBodyAccelerometerJerkMagmean` 
            
* `TimeBodyGyroscopeMagmean`                    
* `TimeBodyGyroscopeJerkMagmean`
                
* `FrequencyBodyAccelerometermeanX`               
* `FrequencyBodyAccelerometermeanY`              
* `FrequencyBodyAccelerometermeanZ`   

* `FrequencyBodyAccelerometermeanFreqX`          
* `FrequencyBodyAccelerometermeanFreqY`           
* `FrequencyBodyAccelerometermeanFreqZ`   
       
* `FrequencyBodyAccelerometerJerkmeanX`          
* `FrequencyBodyAccelerometerJerkmeanY`          
* `FrequencyBodyAccelerometerJerkmeanZ`  

* `FrequencyBodyAccelerometerJerkmeanFreqX`      
* `FrequencyBodyAccelerometerJerkmeanFreqY`       
* `FrequencyBodyAccelerometerJerkmeanFreqZ`
      
* `FrequencyBodyGyroscopemeanX`                   
* `FrequencyBodyGyroscopemeanY`                  
* `FrequencyBodyGyroscopemeanZ` 

* `FrequencyBodyGyroscopemeanFreqX`             
* `FrequencyBodyGyroscopemeanFreqY`               
* `FrequencyBodyGyroscopemeanFreqZ`   
           
* `FrequencyBodyAccelerometerMagmean`             
* `FrequencyBodyAccelerometerMagmeanFreq`      

* `FrequencyBodyAccelerometerJerkMagmean`        
* `FrequencyBodyAccelerometerJerkMagmeanFreq`    

* `FrequencyBodyGyroscopeMagmean`                 
* `FrequencyBodyGyroscopeMagmeanFreq` 

* `FrequencyBodyGyroscopeJerkMagmean`            
* `FrequencyBodyGyroscopeJerkMagmeanFreq`        

* `angleTimeBodyAccelerometerMeangravity`         
* `angleTimeBodyAccelerometerJerkMeangravityMean`

* `angleTimeBodyGyroscopeMeangravityMean`        
* `angleTimeBodyGyroscopeJerkMeangravityMean`   

* `angleXgravityMean`                             
* `angleYgravityMean`                            
* `angleZgravityMean`  

* `TimeBodyAccelerometerstdX`                    
* `TimeBodyAccelerometerstdY`                    
* `TimeBodyAccelerometerstdZ`                    

* `TimeGravityAccelerometerstdX`                  
* `TimeGravityAccelerometerstdY`                 
* `TimeGravityAccelerometerstdZ`                  

* `TimeBodyAccelerometerJerkstdX`                
* `TimeBodyAccelerometerJerkstdY`                 
* `TimeBodyAccelerometerJerkstdZ`                

* `TimeBodyGyroscopestdX`                         
* `TimeBodyGyroscopestdY`                        
* `TimeBodyGyroscopestdZ`                         

* `TimeBodyGyroscopeJerkstdX`                    
* `TimeBodyGyroscopeJerkstdY`                     
* `TimeBodyGyroscopeJerkstdZ`                    

* `TimeBodyAccelerometerMagstd`                   
* `TimeGravityAccelerometerMagstd`               
* `TimeBodyAccelerometerJerkMagstd`               

* `TimeBodyGyroscopeMagstd`                      
* `TimeBodyGyroscopeJerkMagstd`                   

* `FrequencyBodyAccelerometerstdX`               
* `FrequencyBodyAccelerometerstdY`                
* `FrequencyBodyAccelerometerstdZ`               

* `FrequencyBodyAccelerometerJerkstdX`            
* `FrequencyBodyAccelerometerJerkstdY`           
* `FrequencyBodyAccelerometerJerkstdZ`            

* `FrequencyBodyGyroscopestdX`                  
* `FrequencyBodyGyroscopestdY`                    
* `FrequencyBodyGyroscopestdZ`                   

* `FrequencyBodyAccelerometerMagstd`              
* `FrequencyBodyAccelerometerJerkMagstd`        

* `FrequencyBodyGyroscopeMagstd`                
* `FrequencyBodyGyroscopeJerkMagstd`            
